### ISSUE TITLE
Welcome, Daishan

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/python#3]
Hi @DaishanHuang,

Thanks for your fork. I'm so happy that you're interested in this repo. 😸 
I learn python during my free time. Therefore, this repo is not that well maintained as the other ones. Let me know if you need anything, by leaving a comment or raise an issue. Pull request (PR) is welcomed too!! Happy coding & 加油 ~ :grin:

Mincong

**Comment by DaishanHuang** [comment]
Hi @mincong-h Thank you for your warming comment !
As for I learn Python all by self, and have little experience using Github, even not know about any concept 
on the magic technology world , your words are so sweet for a brand new learner .
Hope that I got my meaning expressed well.

**Comment by mincong-h** [comment]
Hi @DaishanHuang,

How are you? I'm sure you can use GitHub to learn many useful frameworks. I've refactored this repository this week, including:

* Adding unit tests
* Formating code

It should make the code reliable and more readable. I'm closing this issue now. Hope you enjoy programming!
